#!/bin/bash
#SBATCH --job-name=profeat_mimic256
#SBATCH --account=ub62
#SBATCH --gres=gpu:V100:1
#SBATCH --partition=m3g
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=16384

module load cuda
python scripts/prepro_feats.py --input_json ../mimic_cxr_256/dataset_m256.json \
	--output_dir ../mimic_cxr_256/m256 \
	--images_root ../mimic_cxr_256/images \
	2>&1 | tee m3/profeat_m256.txt
