#!/bin/bash
#SBATCH --job-name=profeat_retina
#SBATCH --account=ub62
#SBATCH --gres=gpu:V100:1
#SBATCH --partition=m3g
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=16384

module load cuda
python scripts/prepro_feats.py --input_json ../retina_wp/dataset_retina0.json \
	--output_dir ../retina_wp/retina0 \
	--images_root ../retina_resizev2/resize \
	2>&1 | tee m3/profeat_retina0.txt
