#!/bin/bash
#SBATCH --job-name=iu_eval_aoa
#SBATCH --account=bw83
#SBATCH --gres=gpu:V100:1
#SBATCH --partition=m3g
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=16384

module load cuda
python tools/eval.py --input_json ../iu_xray/iu_talk.json --image_root ../iu_xray/images --input_label_h5 ../iu_xray/iu_label.h5 --num_images -1 --model logs/iu_aoa/model-best.pth --infos_path logs/iu_aoa/infos_aoa-best.pkl --language_eval 1 2>&1 | tee eval_aoa.txt
