caption_model: newfc

input_json: ../iu_xray/iu_talk.json
input_att_dir: ../iu_xray/iu_xray_att
input_fc_dir: ../iu_xray/iu_xray_fc
input_label_h5: ../iu_xray/iu_label.h5

learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
# $start_from
checkpoint_path: logs/iu_fc
language_eval: 1
save_checkpoint_every: 1000
val_images_use: 592
save_every_epoch: True
save_history_ckpt: True

batch_size: 10
max_epochs: 30
max_length: 60
train_sample_n: 5
self_critical_after: -1
