caption_model: newfc
input_json: data/mimictalk.json
input_att_dir: data/mimictalk_att
input_fc_dir: data/mimictalk_fc

input_label_h5: data/mimictalk_label.h5
learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
# $start_from
checkpoint_path: logs/mimic_fc
language_eval: 1
save_checkpoint_every: 54317
val_images_use: 7700
save_every_epoch: True
save_history_ckpt: True

batch_size: 10
max_epochs: 30
train_sample_n: 5
self_critical_after: -1