# base
caption_model: att2in2
input_json: data/mimictalk.json
input_att_dir: data/mimictalk_att
input_fc_dir: data/mimictalk_fc

input_label_h5: data/mimictalk_label.h5
learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
checkpoint_path: logs/mimic_a2i2
# $start_from
language_eval: 1
save_checkpoint_every: 3000
val_images_use: 5000

train_sample_n: 5
self_critical_after: 30
batch_size: 10
learning_rate_decay_start: 0
max_epochs: 30
