caption_model: newfc

input_json: ../retina_wp/retina3_talk.json
input_att_dir: ../retina_wp/retina1_att
input_fc_dir: ../retina_wp/retina1_fc
input_label_h5: ../retina_wp/retina3_label.h5

learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
# $start_from
checkpoint_path: logs/r3_fc
language_eval: 1
save_checkpoint_every: 1000
val_images_use: 11539
save_every_epoch: True
save_history_ckpt: True

batch_size: 8
max_epochs: 30
train_sample_n: 5
self_critical_after: -1
max_length: 60
