# base
caption_model: m2transformer_local

input_json: ../retina_wp/retina5_talk.json
input_att_dir: ../retina_wp/retina2_att
input_fc_dir: ../retina_wp/retina2_fc
input_label_h5: ../retina_wp/retina5_label.h5

learning_rate: 0.0005
scheduled_sampling_start: 0
language_eval: 1
save_every_epoch: True
val_images_use: -1
checkpoint_path: logs/r5_m2

save_history_ckpt: True
train_sample_n: 5
self_critical_after: -1
batch_size: 10
learning_rate_decay_start: 0
max_epochs: 30
max_length: 60