# base
caption_model: att2in2
input_json: ../retina_wp/retina0_talk.json
input_att_dir: ../retina_wp/retina0_att
input_fc_dir: ../retina_wp/retina0_fc
input_label_h5: ../retina_wp/retina0_label.h5
learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
checkpoint_path: logs/r0_a2i2v2
# $start_from
language_eval: 1
save_checkpoint_every: 1000
val_images_use: 123918
save_every_epoch: True
save_history_ckpt: True
train_sample_n: 5
self_critical_after: 30
batch_size: 10
max_epochs: 10
max_length: 60
