# base
caption_model: transformer
input_json: ../retina_wp/retina0_talk.json
input_att_dir: ../retina_wp/retina0_att
input_fc_dir: ../retina_wp/retina0_fc
input_label_h5: ../retina_wp/retina0_label.h5

learning_rate: 0.0005
scheduled_sampling_start: 0
checkpoint_path: logs/r0_tfv2
# $start_from
language_eval: 1
#save_checkpoint_every: 3000
save_every_epoch: True
val_images_use: 123918

train_sample_n: 5
self_critical_after: -1
batch_size: 10
learning_rate_decay_start: 0
max_epochs: 10
max_length: 60
